#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), "lib"))
require 'process/highlander/pid'
include Process::Highlander::PID # so there can only be one

require 'deliveryboy/main'
require 'rubygems'
require 'mail'
require 'net/smtp'
require 'yaml'

Deliveryboy::Daemon.new(HashWithIndifferentAccess.new YAML.load(IO.read("#{__FILE__}.yml"))).run
